$schema: https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json
meta:
  version: 1.8.1
  lastModified: 2025-03-11T13:51:14-05:00
  canonical: https://kevin.scontact.info/resume
basics:
  name: Kevin Cefalu
  label: Principal Engineer
  email: kevin@cefalu.rocks
  image: https://psibitengineeringsa.blob.core.windows.net/public/me-sketch.jpg
  location:
    city: Madisonville
    region: Louisiana
    postalCode: 70447-4006
    countryCode: US
  url: https://kevin.scontact.info/
  profiles:
    - network: LinkedIn
      username: kevin-cefalu
      url: https://www.linkedin.com/in/kevin-cefalu/
    - network: Github
      username: kevincefalu
      url: https://www.github.com/kevincefalu/
    - network: Teams
      username: kevin@psibit.engineering
    - network: Discord
      username: psibit
  summary: |
    Kevin Cefalu has over 15 years of experience in software development, systems architecture, leading teams, and mentoring engineers. He has enhanced efficiency and advanced technology across various roles and companies, all while delivering talks on DevOps principles, Microsoft PowerShell, and Azure; topics which reignited his passion for technology at a pivotal moment in his career.

    Over a decade of real-world experience developing applications and automated solutions. Consistently recognized for using technical troubleshooting skills to rapidly, and cost-effectively, resolve challenging issues. Driving force behind DevOps-focused changes to empower developers to rapidly iterate, while protecting the software's underlying infrastructure. Quickly learning and mastering new technology; equally successful in both team and self-directed settings; and proficient in a range of computer systems, languages, tools and testing methodologies.
languages:
  - fluency: Native Speaker
    language: English
work:
  - name: Netchex
    location: Covington, LA 70433
    position: Principal Site Reliability Engineer
    startDate: 2017-08
    summary: |
      Started as Software Engineer and progressed through DevOps Engineering and Management roles to Principal Site Reliability Engineer.
    highlights:
      - Developed PowerShell scripts & modules to automate tasks and improve the quality of existing automation
      - Designed, created & managed three Azure Kubernetes services (Development, Staging, and Production)
      - Overhauled manual process of building "team" development environments, reducing work from over a month to 4.5 hours
      - Automated cloud and localhost environment state management using PowerShell on Azure Automation accounts
      - Created PowerShell desired state configurations to simplify developer laptop and server setup
      - Developed a portal to assist in off-loading and automating repetitive tasks
      - Maintained and enhanced developer environment automation repository using Packer and Vagrant
      - Rewrote legacy code to stateless, microservice architecture
      - Developed massive repository of infrastructure as code (IaC) for Azure cloud environments
      - Developed a framework for Robotic Process Automation (RPA) utilizing Selenium web drivers
  - name: Pool Corporation
    location: Covington, LA 70433
    position: Software Engineer II
    startDate: 2012-11
    endDate: 2017-08
    summary: |
      Developed several applications used by internal employees and customers, specializing in B2B ecommerce websites.
    highlights:
      - Main point of contact, nationally, for training and support of B2B platform (including travel for on-site support)
      - Created a custom library to integrate a Google Search Appliance
      - Overhauled WCF service used to communicate with mobile apps
      - Complete re-architecture of B2B core
      - Developed custom integrations for Skype for Business
      - Tested technologies like Docker and Neo4j for use in applications
  - name: University of New Orleans
    location: New Orleans, LA 70148
    position: Web Developer
    startDate: 2009-03
    endDate: 2012-11
    summary: |
      Developed custom applications and business logic for installed applications.
    highlights:
      - Worked with PeopleSoft, MS Exchange, Microsoft Lync, DotNetNuke, SharePoint, etc.
      - Redesigned old web services and processes to increase user efficiency, optimization, and maintainability
      - Understood client needs and produced final, polished solutions based on requirements
      - Previously served as Help Desk Analyst / Help Desk Student Manager (2009-2011)
      - Handled technical troubleshooting within enterprise environment
      - Developed and updated the UCC website
      - Aided in development of decision engine software
skills:
  - name: Visual Studio & Visual Studio Code
  - name: Automation
  - name: Continuous Integration & Delivery (CI/CD)
  - name: DevOps
  - name: Infrastructure as code (IaC)
  - name: Strategic Planning
  - name: Leadership
  - name: People Management
  - name: PowerShell
    keywords:
      - PowerShell Scripting
      - PowerShell Modules
      - Desired State Configuration (DSC)
      - Robotic Process Automation
  - name: Microsoft Azure
    keywords:
      - Azure Resource Manager (ARM)
      - Azure Bicep
      - Azure PowerShell
      - Azure CLI
      - .NET Management & Client SDKs
      - Azure Kubernetes Service (AKS)
      - Azure Automation
      - CosmosDB
      - Application Gateways
      - Key Vaults
      - Container Registries
  - name: Microsoft Azure DevOps
    keywords:
      - Azure Pipelines
      - Pipeline Automation
  - name: C#
  - name: ASP.NET
    keywords:
      - ASP.NET WebAPI
      - Legacy ASP
      - VB.NET
  - name: Microsoft SQL Server
  - name: Microsoft Windows (Desktop & Server)
  - name: Microsoft Active Directory
  - name: Microsoft Entra Id
  - name: Kubernetes
  - name: Docker
  - name: Selenium
  - name: React.js
  - name: MongoDB
  - name: Packer
  - name: Vagrant
education:
  - institution: University of Louisiana at Lafayette
    studyType: Bachelor
    area: Electrical Engineering, Graphic Design, & Computer Science
    startDate: 2004-08
    endDate: 2008-12
  - institution: Southeastern Louisiana University
    studyType: Bachelor
    area: Computer Science
    startDate: 2009-01
    endDate: 2010-12
  - institution: University of New Orleans
    studyType: Bachelor
    area: Computer Science
    startDate: 2010-01
    endDate: 2012-12
certificates:
  - name: 'Azure Administrator Associate'
    issuer: Microsoft
    date: 2023-10-01
    url: http://learn.microsoft.com/en-us/users/kevincefalu/credentials/efba71019bddde2d
publications:
  - name: 'Azure Automation with PowerShell: Scripting Away the Problems of Yesterday'
    publisher: 'SQL Saturday #867 - Baton Rouge 2019'
    date: 2019-08-17
    url: http://sqlsaturday.com/2019-08-17-SQLSat-0867
  - name: 'What the #@&% is DevOps, Anyways? A Presentation on DevOps, and Why You Should Care.'
    publisher: 'SELU ACM - March 2020'
    date: 2020-03-10
    url: http://github.com/kevinCefalu/Presentations/tree/master/src/instances/2020-What-the-____-Is-DevOps-Anyways
  - name: 'Don''t Skip ARM Day: Your Bicep Will Thank You'
    publisher: 'PowerShell + DevOps Global Summit Lightning Talk'
    date: 2023-04-27
    url: http://github.com/kevinCefalu/Presentations/tree/master/src/instances/2023-Dont-Skip-ARM-Day
  - name: 'Peer-to-Peer PowerShell: The Ins and Outs of Pair Programming'
    publisher: 'PowerShell + DevOps Global Summit'
    date: 2024-04-09
    releaseDate: 2024-05-23
    url: http://www.youtube.com/watch?v=Xw5-SGH-pBk
  - name: 'The PowerShell and DevOps Global Summit 2023 Bar Sessions'
    publisher: 'The PowerShell Podcast'
    date: 2024-04-27
    url: https://powershell.org/2023/04/the-powershell-podcast-powershell-and-devops-global-summit-the-bar-sessions/
  - name: 'Breaking Down Barriers in PowerShell and Management with Kevin Cefalu'
    publisher: 'The PowerShell Podcast'
    date: 2023-12-04
    url: https://powershell.org/2023/12/the-powershell-podcast-breaking-down-barriers-in-powershell-and-management-with-kevin-cefalu/
  - name: 'The PowerShell & DevOps Global Summit 2024 Bar Session 1'
    publisher: 'The PowerShell Podcast'
    date: 2024-04-11
    url: https://powershell.org/2024/04/the-powershell-podcast-the-powershell-devops-global-summit-2024-bar-session-1/
interests:
  - name: 'Computer-aided Design (CAD)'
  - name: '3D Printing'
    keywords:
      - Fused deposition modeling (FDM)
  - name: 'Home Automation'
  - name: 'Woodworking'
  - name: 'Electronics'
  - name: 'Gaming'
  - name: 'Music'
  - name: 'Drawing & Design'
  - name: 'Mental Health'
projects: []
references: []
