$schema: https://raw.githubusercontent.com/jsonresume/resume-schema/v1.0.0/schema.json
meta:
  version: 1.8.1
  lastModified: 2025-03-14T16:50:00-05:00
  canonical: https://kevin.scontact.info/resume/archived
work:
  - name: Ferrara Fire Apparatus
    location: Holden, LA 70744
    position: Under-body Electrical Specialist
    startDate: 2008-06
    endDate: 2008-03
    summary: '* Responsible for several key electrical harnesses in both\nthe under-body and cab of errara fire engines.\n* Substituted for and assisted other electricians with their\ntasks,while completing my own.'
    highlights: []
  - name: Directech Southwest
    location: Baton Rouge, LA 70817
    position: Installation & Service Technician
    startDate: 2007-09
    endDate: 2007-11
    summary: 'Leading technician in High Definition service and installation for Directv satellite television. Was required to interface with high level, dedicated satellite equipment to pinpoint and lock-in signals from up to 6 satellites, troubleshoot dielectric cable lines, and ensure quality work from myself and other technicians that I was required to perform Quality Control (QC) checks on. * Completed,on average,5-6 calls per day.\n* Was the leading technician in HD service and installation.\n* Operated out of my personal vehicle.'
    highlights: []
  - name: Giles Nissan
    location: Lafayette, LA 70503
    position: Sales Consultant
    startDate: 2007-04
    endDate: 2007-09
    summary: '' # TODO
    highlights:
      - Sold, on average, seven cars per month
      - Sold the most cars in a single month (14)
  - name: Magellan Construction
    location: Lafayette, LA 70508
    startDate: 2006-11
    endDate: 2007-04
    summary: '* Residential remodeling and new construction.\n* Commercial new construction.\n* Used hand,power,pneumatic,and heavy machinery tools.'
    highlights: []
  - name: Advanced Radiographics, Inc. & Datafiles
    location: Duson, LA 70529
    position: Digital Records Clerk, Server Adminisitrator, & After-Hours Medical Courier
    startDate: 2005-02
    endDate: 2006-11
    summary: '* Overtime workload to aid company in taking on more\ncustomers.\n* Customer service representative to hospitals and\ndoctors offices across southern Louisiana. Customer Service representative to hospitals and doctors'' offices across southern Louisiana. Usage and maintenance of high-capacity/speed medical document scanners to digitize and catalogue confidential information within a Windows 2k3 server. Required to be on call virtually 24 hours a day to provide support in the event of server and/or network malfunctions.'
    highlights: []
  - name: Lowe's Home Improvement
    location: Covington, LA
    position: Electrical Department Sales Associate
    startDate: 2004-01
    endDate: 2005-02
    summary: '' # TODO
  - name: Southern Oaks Plantation
    location: Covington, LA
    position: Staff Member
    startDate: 2003-06
    endDate: 2003-12
    summary: '' # TODO
    highlights:
      - Assisted with facility maintenance outside of normal business hours
  - name: Macaroni Grill
    location: Mandeville, LA
    position: Brick Oven Chef
    startDate: 2002-08
    endDate: 2003-06
    summary: '' # TODO